INSERT INTO camp (name, description, location, capacity, min_age, max_age, start_date, end_date, image)
VALUES ('Camp North Star',
        'A fun way to get your kids out of your hair!',
        'Seattle, WA',
        '50',
        '7',
        '12',
        '2020-06-07',
        '2020-07-02',
        '../best-family-summer-camp-canoeing.jpg'),
       ('Camp Crystal Lake',
        'A fun getaway for your teen/young adult to spend some time away from their screens!',
        'Bend, OR',
        '75',
        '13',
        '20',
        '2020-07-10',
        '2020-07-31',
        '../webcover.jpg'),
       ('Camp Anawanna',
        'A fun getaway for the grown-ups to have grown-up time... with grown-ups!',
        'Portland, OR',
        '100',
        '21',
        '100',
        '2020-07-10',
        '2020-07-31',
        '../Camp-grown-ups-MAIN.jpg');