INSERT INTO camp (name, description, location, capacity, min_age, max_age, start_date, end_date, image, about)
VALUES ('Camp North Star',
        'A fun way to get your kids out of your hair!',
        'Seattle, WA',
        '50',
        '7',
        '12',
        '2020-06-07',
        '2020-07-02',
        '../best-family-summer-camp-canoeing.jpg', 'Camp Northstar is the place to be for youngins this summer! Our campers will have an action-packed month full of various sports, activities, and crafts! They will also come back home with new leadership skills and tons of friends. Sign your child up for Camp North Star today!'),
       ('Camp Crystal Lake',
        'A fun getaway for your teen/young adult to spend some time away from their screens!',
        'Bend, OR',
        '75',
        '13',
        '20',
        '2020-07-10',
        '2020-07-31',
        '../webcover.jpg', 'Camp Crystal Lake offers teens and young adults a jam-packed month of adventure hikes, water and boating activities, competitve sports, and much more! Our skilled staff are there to ensure the saftey of the campers in all activities, and also to ensure our campers have the time of their lives! Enroll for CampCrystal Lake today!'),
       ('Camp Anawanna',
        'A fun getaway for the grown-ups to have grown-up time... with grown-ups!',
        'Portland, OR',
        '100',
        '21',
        '100',
        '2020-07-10',
        '2020-07-31',
        '../Camp-grown-ups-MAIN.jpg', 'Forget what you know about summer camp, this one is for the grown-ups! Leave your kids at home and come and join us for awesome hikes, relaxing spas, luxurious lodging, gorgeous landscapes, and a very well-equipped kaeside bar. Sign up for Camp Anawanna with a friend for a discount or come solo and meet new people! We are excited to have you!');